org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.user.home=.gradle-neoforge

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neoforge_version=21.1
neoforge_version_range=[21.1,)
loader_version_range=[4,)

mapping_channel=official
mapping_version=1.21.1

mod_id=twilight_lib
mod_name=Twilight Lib
mod_license=All Rights Reserved
mod_version=2.0.0
mod_group_id=mc.sayda.twilight_lib
mod_authors=mc_jojo3
mod_description=Twilight Lib is a library mod used by mc_jojo3's mods.
