plugins {
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = rootProject.mod_group_id
archivesBaseName = "twilight_lib-1.20.1-forge"

architectury {
    platformSetupLoomIde()
    forge()
}

loom {
    accessWidenerPath = project(":1.20.1:common").loom.accessWidenerPath
    mixin.defaultRefmapName = "twilight_lib-forge.refmap.json"
    forge {
        mixinConfig "twilight_lib-common.mixins.json"
        mixinConfig "twilight_lib-forge.mixins.json"
    }
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin because we don't want IDEA to index this.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common
}

dependencies {
    forge "net.minecraftforge:forge:${rootProject.property('1_20_1_minecraft_version')}-${rootProject.property('1_20_1_forge_version')}"
    modApi "dev.architectury:architectury-forge:${rootProject.property('1_20_1_architectury_version')}"

    common(project(path: ":1.20.1:common", configuration: "namedElements")) { transitive = false }
    shadowCommon(project(path: ":1.20.1:common", configuration: "transformProductionForge")) { transitive = false }

}

processResources {
    var replaceProperties = [
            minecraft_version: rootProject.property('1_20_1_minecraft_version'),
            minecraft_version_range: "[1.20.1,1.21)",
            forge_version: rootProject.property('1_20_1_forge_version'),
            forge_version_range: "[47,)",
            loader_version_range: "[37,)",
            mod_id: rootProject.mod_id,
            mod_name: rootProject.mod_name,
            mod_license: rootProject.mod_license,
            mod_version: rootProject.mod_version,
            mod_authors: rootProject.mod_authors,
            mod_description: rootProject.mod_description,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

shadowJar {
    exclude "fabric.mod.json"
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier = null
}

jar {
    archiveClassifier = "dev"
}

sourcesJar {
    def commonSources = project(":1.20.1:common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}
